# Problem Statement 1:
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [3]:
import numpy as np

def vandermonte_matrix(input_vector,increasing):
    output_array=np.zeros((1,len(input_vector)))
    input_array=np.array(input_vector)
    
    if increasing:
        for i in range(len(input_vector)):
            output_array=np.vstack((output_array,input_array**i))
            
    else:
        for i in range(len(input_vector)-1,-1,-1):
            output_array=np.vstack((output_array,input_array**i))
    
    output_vector = np.array(output_array[1:,:]).astype(int)
    return output_vector.T
    
    
input_vector=input("Please provide an input vector:")
input_list=list(map(lambda x:int(x),input_vector.split(",")))
print("Input Vector is:",input_list)
print(vandermonte_matrix(input_list,True))

Please provide an input vector:1,2,4,6,8
Input Vector is: [1, 2, 4, 6, 8]
[[   1    1    1    1    1]
 [   1    2    4    8   16]
 [   1    4   16   64  256]
 [   1    6   36  216 1296]
 [   1    8   64  512 4096]]


# Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.
Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [1]:
import numpy as np

def moving_average(input_seq,window):
    seq_list=list(map(lambda x:int(x),input_seq.split(",")))
    seq_array=np.array(seq_list)
    
    num_op = np.size(seq_array)-window+1
    for i in range(num_op):
        print(np.sum(seq_array[i:i+window])/window)
    
input_seq = input("Please enter a sequence of values:")
window=int(input("Please enter a value for window size:"))

moving_average(input_seq,window)

Please enter a sequence of values:3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150
Please enter a value for window size:3
5.0
4.666666666666667
5.666666666666667
6.666666666666667
9.666666666666666
28.666666666666668
49.333333333333336
72.66666666666667
84.0
93.33333333333333
116.33333333333333
